### ISSUE TITLE
Add window context options on right click to tracker

### ISSUE THREAD

**Issue by John-Dean** [Zerthox/arcdps-food-reminder#17]
Hello,

I'm trying to right click the tracer window for the context options where you can set the window position, enable/disable the background and window title etc.

This doesn't seem to work.

This addon: https://github.com/Krappa322/arcdps_healing_stats seems to have this functionality down well, so it seems to be an addon issue not an arc issue.

Any chance this could be resolved?

Kind regards,
John

**Comment by Zerthox** [comment]
Yes, the context menu with window options has to be implemented manually in every addon. So this would be a new feature to develop rather than a bug to fix.
